[package]
name = "beethoven-core"
description = "Core traits for Beethoven - Swap and Deposit"
version = "0.0.1"
license = "MIT"
edition = "2021"

[dependencies]
solana-account-view.workspace = true
solana-instruction-view = { workspace = true, features = ["cpi"] }
solana-program-error.workspace = true

[lib]
test = false
doctest = false
