[package]
name = "beethoven-test"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
test = false

[features]
default = []
upstream-bpf = ["dep:solana-define-syscall"]

[dependencies]
beethoven = { workspace = true, features = ["deposit", "swap"] }
pinocchio.workspace = true
pinocchio-token.workspace = true
pinocchio-token-2022.workspace = true
solana-define-syscall = { workspace = true, features = [
    "unstable-static-syscalls",
], optional = true }
